=== Jolutase827/EasyPass/XML/proyecto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT em (usuarios,curriculums)>
<!ELEMENT curriculums (cv*)>
<!ELEMENT cv (titulo,formacion,experiencia)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT formacion (titulacion*,idioma*)>
<!ELEMENT experiencia (item*)>
<!ELEMENT titulacion (nombre,fecha,centro)>
<!ELEMENT idioma (nombre,nivel,certificado)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT certificado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT centro (#PCDATA)>
<!ELEMENT item (titulo,sector,descripcion,fecha_inicio,fecha_fin)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>
<!ATTLIST cv cuenta CDATA #IMPLIED>
<!ATTLIST cv id CDATA #REQUIRED>
<!ELEMENT usuarios (root, noroot)>
<!ELEMENT root (usuario)>
<!ELEMENT noroot (usuariosnoroot,empresas)>
<!ELEMENT usuariosnoroot (usuario*)>
<!ELEMENT empresas (usuario*)>
<!ELEMENT usuario (nombre,sector?,correo?,contrasenya,imagen?,mas_datos?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT contrasenya (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT mas_datos (#PCDATA)>
<!ELEMENT sector (#PCDATA)>

=== Jolutase827/EasyPass/archivo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE em SYSTEM "../XML/proyecto.dtd">
<em>
    <usuarios>
        <root>
            <usuario>
                <nombre>root</nombre>
                <contrasenya>1234</contrasenya>
                <imagen>imagenUsuario.png</imagen>
            </usuario>
        </root>
        <noroot>
        <usuariosnoroot>
            <usuario>
                <nombre>Jose Luis</nombre>
                <correo>cau01111@gmail.com</correo>
                <contrasenya>1234</contrasenya>
                <imagen>https://cdn01.segre.com/uploads/imagenes/bajacalidad/2022/06/02/_pacoretocat_ad1a584f.jpg?5b401d175a16dc2d57257136af48ed0a</imagen>
                <mas_datos>
                </mas_datos>
            </usuario>
            <usuario>
                <nombre>marta</nombre>
                <correo>cau01111@gmail.com</correo>
                <contrasenya>1234</contrasenya>
                <imagen>imagenUsuario.png</imagen>
                <mas_datos>
                </mas_datos>
            </usuario>
            <usuario>
                <nombre>marcela</nombre>
                <correo>cau01111@gmail.com</correo>
                <contrasenya>1234</contrasenya>
                <imagen>imagenUsuario.png</imagen>
                <mas_datos>
                </mas_datos>
            </usuario>
        </usuariosnoroot>
            <empresas>
            </empresas>
        </noroot>
        
    </usuarios>
</em>

=== Jolutase827/EasyPass/XML/proyecto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE em SYSTEM "../XML/proyecto.dtd">
<em>
    <usuarios>
        <root>
            <usuario>
                <nombre>root</nombre>
                <contrasenya>1234</contrasenya>
                <imagen>imagenUsuario.png</imagen>
            </usuario>
        </root>
        <noroot>
        <usuariosnoroot>
            <usuario>
                <nombre>Jose Luis</nombre>
                <correo>cau01111@gmail.com</correo>
                <contrasenya>1234</contrasenya>
                <imagen>https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Mercedes-Benz_Star_2022.svg/800px-Mercedes-Benz_Star_2022.svg.png</imagen>
                <mas_datos>
                </mas_datos>
            </usuario>
            <usuario>
                <nombre>marta</nombre>
                <correo>cau01111@gmail.com</correo>
                <contrasenya>1234</contrasenya>
                <imagen>imagenUsuario.png</imagen>
                <mas_datos>
                </mas_datos>
            </usuario>
            <usuario>
                <nombre>marcela</nombre>
                <correo>cau01111@gmail.com</correo>
                <contrasenya>1234</contrasenya>
                <imagen>imagenUsuario.png</imagen>
                <mas_datos>
                </mas_datos>
            </usuario>
        </usuariosnoroot>
            <empresas>
            </empresas>
        </noroot>
    </usuarios>
    <curriculums>
        <cv id="0">
            <titulo></titulo>
            <formacion>
                <titulacion>
                    <nombre></nombre>
                    <fecha></fecha>
                    <centro></centro>
                </titulacion>
                <idioma>
                    <nombre></nombre>
                    <nivel></nivel>
                    <certificado></certificado>
                </idioma>
            </formacion>
            <experiencia>
                <item>
                    <titulo></titulo>
                    <sector></sector>
                    <descripcion></descripcion>
                    <fecha_inicio></fecha_inicio>
                    <fecha_fin></fecha_fin>
                </item>
            </experiencia>
        </cv>
    </curriculums>
</em>
